CREATE TABLE IF NOT EXISTS DECKS (NAME TEXT PRIMARY KEY, LANGUAGE TEXT);
CREATE TABLE IF NOT EXISTS WORDS(WORD TEXT PRIMARY KEY, TRANSLATION TEXT, DECK TEXT, LEVEL INT, NEXT_STUDY DATETIME);
CREATE TABLE IF NOT EXISTS AUDIO(WORD TEXT, DECK TEXT,  AUDIO BLOB);

INSERT OR IGNORE INTO  DECKS (NAME, LANGUAGE) VALUES('VIETNAMESE', 'VIETNAMESE');